import pyautogui
from win32api import GetSystemMetrics
import os

# Disable PyAutoGUI fail-safe
pyautogui.FAILSAFE = False

print("SalesMate + Backup Menu Test")

# Create a Database Backup directory called SMP
path = "C:/SMP"
if not os.path.exists(path):
    os.makedirs(path)

# Get the width and height of the monitor
width = GetSystemMetrics(0)
height = GetSystemMetrics(1)

# Click on the bottom-left corner to launch the Start menu
print("Click on the bottom-center to launch the Start menu")
pyautogui.click(450, 1080)
print("Select the SalesMate + Application")
pyautogui.typewrite("SalesMate +")
print("Press Enter Key to Launch SalesMate + Application and Wait for 10 Sec")
pyautogui.press("enter",1,10)#Sometimes SalesMate + might take 10 seconds to load it . So 10 sec delay
print("Press Enter Key again to close the Tip Of the Day Dialog")
pyautogui.press("enter")
print("Now alt and f shortcut key in  Salesmate to invoke the File Root menu")
pyautogui.press(['alt','f'])
print("Now press 'b' to invoke the Bacuup Folder Dialog")
pyautogui.press("b",1,2)
print("Go to D Drive")
pyautogui.press("d",1,1)
print("Now press Right arrow Key to Expand the Tree")
pyautogui.press("right",1,1)
print("Go to SMP Folder")
pyautogui.typewrite("smp")
print("Press Enter Key to Backuup Data")
pyautogui.press("enter",1,2)
print("Press Enter Again to Close the OK Button")
pyautogui.press("enter")
print("now alt and e shortcut key in salemate to invoke the setup menu")
pyautogui.press(['alt','e'])
print("press the v button to open service")
pyautogui.press("v")
print("press the new key for add service details")
pyautogui.press("N")
print("enter the service id")
pyautogui.typewrite("9")
pyautogui.press("enter")
print("enter the service name")
pyautogui.typewrite("sales tax")
pyautogui.press("enter")
print("enter the describtion")
pyautogui.typewrite("1000")
pyautogui.press("enter")
print("enter the standard rate")
pyautogui.typewrite("0.00")
pyautogui.press("enter")
pyautogui.press("enter",1,2)
pyautogui.press("enter",1,2)
pyautogui.press('C',1,3)
print("press the customer key")
pyautogui.press(['alt','C'])
print("prees A to add the customer")
pyautogui.press("A")
pyautogui.press("enter")
print("enter the customer id")
pyautogui.typewrite("3")
pyautogui.press("enter")
print("enter the first name of the customer")
pyautogui.typewrite("neena")
pyautogui.press("enter")
print("enter the last name of the customer")
pyautogui.typewrite("varghese")
pyautogui.press("enter")
pyautogui.typewrite("Ms")
pyautogui.press("enter")
pyautogui.typewrite("chengalathu(h)")
pyautogui.press("enter")
pyautogui.typewrite("7306564014")
pyautogui.press("enter")
pyautogui.typewrite("neenachengalathu@gmail.com")
pyautogui.press("enter")
pyautogui.press("enter")
pyautogui.press("enter")
pyautogui.press("enter")
pyautogui.press('a')
pyautogui.press("enter")
